apiVersion: v1
kind: Secret

metadata:
  name: cloudflare-secret
  namespace: cloudflare-network

type: Opaque

stringData:
  tunnel-token: eyJhIjoiOTA0YjY0NGQxY2I5MDEyNzUwOGJkOGQwNTE1ZWE2NWYiLCJ0IjoiMWM5ZjRlNGEtZWQzMS00NjdjLWIyOWEtZTM1MDZiNzFkZTUwIiwicyI6Ik1UazFOR1JqWWpZdE9UQmlaaTAwTldZMUxUZzJZbUV0WWpsaE5ESTBNemczWlRrMiJ9
